export enum TokenSymbol {
    BTC = 'BTC',
    WBTC = 'WBTC',
    IUSD = 'iUSD',
    BIUU = 'BIUU',
    HUHU = 'HUHU',
    VOYA = 'VOYA',
    JEFF = 'JEFF',
    ELXR = 'ELXR',
    SPELL = 'SPELL',
    MRC404 = 'MRC404',
    WIZARD = 'Wizard',
    MERLINPAD ='MerlinPad',
    BALL = 'BALL',
    OWL = 'Owl',
    MERLINMEME = 'MERLIN(Meme)',
    DRAGON = 'DRAGON',
    ART = 'ART',
    MERLINBOX = 'MerlinBox',
    MERLINLAND = 'MerlinLand',
    RAT404 = 'RAT404',
    SAILOR = 'Sailor',
}
